"""Real-Time News Analyst — RSS feeds -> Claude analysis -> daily email digest"""
import anthropic, feedparser, smtplib, json, os, schedule, time
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

client = anthropic.Anthropic()

FEEDS = {
    "Economic Times Markets": "https://economictimes.indiatimes.com/markets/rss.cms",
    "MoneyControl": "https://www.moneycontrol.com/rss/latestnews.xml",
    "Reuters Business": "https://feeds.reuters.com/reuters/businessNews",
    "Bloomberg Markets": "https://feeds.bloomberg.com/markets/news.rss",
    "NSE News": "https://www.nseindia.com/rss",
}

def fetch_articles(max_per_feed: int = 10) -> list[dict]:
    articles = []
    for source, url in FEEDS.items():
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:max_per_feed]:
                articles.append({
                    "source": source,
                    "title": entry.get("title", ""),
                    "summary": entry.get("summary", entry.get("description", ""))[:500],
                    "link": entry.get("link", ""),
                    "published": entry.get("published", ""),
                })
        except Exception as e:
            print(f"Error fetching {source}: {e}")
    return articles

def analyze_news(articles: list[dict], focus: str = "Indian markets") -> dict:
    articles_text = "\n\n".join([
        f"SOURCE: {a['source']}\nTITLE: {a['title']}\nSUMMARY: {a['summary']}"
        for a in articles[:30]
    ])

    prompt = f"""Analyze these news articles for an investor focused on {focus}.

ARTICLES:
{articles_text}

Provide JSON analysis:
{{
  "market_sentiment": "<Bullish/Bearish/Neutral/Mixed>",
  "sentiment_score": <-100 to 100>,
  "top_themes": ["theme1", "theme2", "theme3"],
  "key_events": [
    {{"event": "...", "impact": "<Positive/Negative/Neutral>", "sectors_affected": ["..."]}}
  ],
  "sector_outlook": {{
    "IT": "<outlook>", "Banking": "<outlook>", "Energy": "<outlook>", "FMCG": "<outlook>"
  }},
  "investment_thesis": "<2-3 sentences on what this news means for investors>",
  "stocks_mentioned": ["stock1", "stock2"],
  "risks_to_watch": ["risk1", "risk2"],
  "opportunities": ["opportunity1", "opportunity2"],
  "summary": "<executive summary in 3-4 sentences>"
}}
Return ONLY valid JSON."""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1200,
        messages=[{"role": "user", "content": prompt}]
    )
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"): raw = raw[4:]
    return json.loads(raw.strip())

def format_email(analysis: dict, articles: list[dict]) -> tuple[str, str]:
    date = datetime.now().strftime("%B %d, %Y")
    sentiment = analysis.get("market_sentiment", "Neutral")
    emoji = {"Bullish": "🟢", "Bearish": "🔴", "Neutral": "🟡", "Mixed": "🟠"}.get(sentiment, "⚪")

    subject = f"📰 AI Market Digest — {date} | {emoji} {sentiment}"

    html = f"""<html><body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;color:#333">
<h1 style="color:#1a73e8">📰 Market Digest — {date}</h1>
<div style="background:#f8f9fa;padding:16px;border-radius:8px;border-left:4px solid {'#22c55e' if sentiment=='Bullish' else '#ef4444' if sentiment=='Bearish' else '#f59e0b'}">
<h2>{emoji} {sentiment} Sentiment ({analysis.get('sentiment_score', 0):+d}/100)</h2>
<p>{analysis.get('summary', '')}</p>
</div>
<h3>🎯 Investment Thesis</h3>
<p>{analysis.get('investment_thesis', '')}</p>
<h3>📈 Top Themes</h3>
<ul>{''.join(f'<li>{t}</li>' for t in analysis.get('top_themes', []))}</ul>
<h3>⚡ Key Events</h3>
{''.join(f'<div style="padding:8px;margin:4px 0;background:#fff;border:1px solid #e0e0e0;border-radius:4px"><strong>{e.get("event","")}</strong> — {e.get("impact","")}<br><small>Sectors: {", ".join(e.get("sectors_affected",[]))}</small></div>' for e in analysis.get('key_events',[])[:5])}
<h3>⚠️ Risks to Watch</h3>
<ul>{''.join(f'<li>{r}</li>' for r in analysis.get('risks_to_watch',[]))}</ul>
<h3>💡 Opportunities</h3>
<ul>{''.join(f'<li>{o}</li>' for o in analysis.get('opportunities',[]))}</ul>
<hr><p style="color:#999;font-size:12px">Generated by AI · Not financial advice · {len(articles)} articles analyzed</p>
</body></html>"""
    return subject, html

def send_email(subject: str, html: str, to_email: str):
    smtp_user = os.environ.get("SMTP_USER", "")
    smtp_pass = os.environ.get("SMTP_PASS", "")
    if not smtp_user:
        print("No SMTP configured. Printing digest:")
        print(subject)
        return
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = smtp_user
    msg['To'] = to_email
    msg.attach(MIMEText(html, 'html'))
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, to_email, msg.as_string())
    print(f"Email sent to {to_email}")

def run_daily_digest():
    print(f"[{datetime.now().strftime('%H:%M')}] Running news analysis...")
    articles = fetch_articles()
    print(f"Fetched {len(articles)} articles")
    analysis = analyze_news(articles)
    subject, html = format_email(analysis, articles)
    to_email = os.environ.get("DIGEST_EMAIL", "")
    if to_email:
        send_email(subject, html, to_email)
    print(f"Sentiment: {analysis.get('market_sentiment')} ({analysis.get('sentiment_score'):+d})")
    print(f"Themes: {', '.join(analysis.get('top_themes', []))}")
    return analysis

if __name__ == "__main__":
    import sys
    if "--schedule" in sys.argv:
        schedule.every().day.at("07:00").do(run_daily_digest)
        print("Scheduled daily digest at 7:00 AM")
        while True:
            schedule.run_pending()
            time.sleep(60)
    else:
        run_daily_digest()
